# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/add_task_widget.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(426, 506)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/png/tray.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setWindowOpacity(0.95)
        self.gridLayout_4 = QtWidgets.QGridLayout(Form)
        self.gridLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.comboBox_priority = QtWidgets.QComboBox(Form)
        self.comboBox_priority.setObjectName("comboBox_priority")
        self.horizontalLayout_4.addWidget(self.comboBox_priority)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.timeEdit = QtWidgets.QTimeEdit(Form)
        self.timeEdit.setObjectName("timeEdit")
        self.horizontalLayout_4.addWidget(self.timeEdit)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_4)
        self.checkBox_cyclic = QtWidgets.QCheckBox(Form)
        self.checkBox_cyclic.setStyleSheet("")
        self.checkBox_cyclic.setObjectName("checkBox_cyclic")
        self.horizontalLayout_3.addWidget(self.checkBox_cyclic)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.comboBox_event = QtWidgets.QComboBox(Form)
        self.comboBox_event.setObjectName("comboBox_event")
        self.horizontalLayout_3.addWidget(self.comboBox_event)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit.setMinimumSize(QtCore.QSize(300, 70))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_3.addWidget(self.plainTextEdit, 3, 0, 1, 1)
        self.calendarWidget = QtWidgets.QCalendarWidget(Form)
        self.calendarWidget.setMinimumSize(QtCore.QSize(300, 250))
        self.calendarWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.calendarWidget.setObjectName("calendarWidget")
        self.gridLayout_3.addWidget(self.calendarWidget, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_ok = QtWidgets.QPushButton(Form)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout_5.addWidget(self.pushButton_ok)
        self.pushButton_done = QtWidgets.QPushButton(Form)
        self.pushButton_done.setObjectName("pushButton_done")
        self.horizontalLayout_5.addWidget(self.pushButton_done)
        self.pushButton_cancel = QtWidgets.QPushButton(Form)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout_5.addWidget(self.pushButton_cancel)
        self.pushButton_delete = QtWidgets.QPushButton(Form)
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.horizontalLayout_5.addWidget(self.pushButton_delete)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 5, 0, 1, 1)
        self.pushButton_show_idea = QtWidgets.QPushButton(Form)
        self.pushButton_show_idea.setObjectName("pushButton_show_idea")
        self.gridLayout_3.addWidget(self.pushButton_show_idea, 4, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(-1, 2, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setMinimumSize(QtCore.QSize(38, 38))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_9.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setHorizontalSpacing(0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.toolButton_close = QtWidgets.QToolButton(self.frame_2)
        self.toolButton_close.setMinimumSize(QtCore.QSize(32, 32))
        self.toolButton_close.setMaximumSize(QtCore.QSize(32, 32))
        self.toolButton_close.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/png/cross.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_close.setIcon(icon1)
        self.toolButton_close.setIconSize(QtCore.QSize(48, 48))
        self.toolButton_close.setObjectName("toolButton_close")
        self.gridLayout_9.addWidget(self.toolButton_close, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_2)
        self.gridLayout_4.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Task"))
        self.label_5.setText(_translate("Form", "Hour:"))
        self.checkBox_cyclic.setText(_translate("Form", "Daily"))
        self.label_6.setText(_translate("Form", "Action:"))
        self.plainTextEdit.setPlaceholderText(_translate("Form", "Short task description"))
        self.pushButton_ok.setText(_translate("Form", "Ok"))
        self.pushButton_done.setText(_translate("Form", "Set done"))
        self.pushButton_cancel.setText(_translate("Form", "Cancel"))
        self.pushButton_delete.setText(_translate("Form", "Delete"))
        self.pushButton_show_idea.setText(_translate("Form", "Show idea"))
        self.label_7.setText(_translate("Form", "Add/edit task"))
        self.toolButton_close.setToolTip(_translate("Form", "Close"))
        self.toolButton_close.setText(_translate("Form", "..."))

import resources_rc
