# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(506, 728)
        MainWindow.setMinimumSize(QtCore.QSize(400, 450))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 1400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/png/tray.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(0.9)
        MainWindow.setStyleSheet("QAbstractItemView {\n"
"color:#666;\n"
"}\n"
"\n"
"QComboBox {\n"
"border-style: solid;\n"
"border-color:lightgray;\n"
"border-width: 1px;\n"
"color:#A1A1A1;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(200, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_8.setContentsMargins(0, 4, 0, 4)
        self.gridLayout_8.setHorizontalSpacing(4)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.toolButton_24h = QtWidgets.QToolButton(self.frame)
        self.toolButton_24h.setMinimumSize(QtCore.QSize(32, 32))
        self.toolButton_24h.setMaximumSize(QtCore.QSize(40, 40))
        self.toolButton_24h.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/png/2441.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_24h.setIcon(icon1)
        self.toolButton_24h.setIconSize(QtCore.QSize(48, 48))
        self.toolButton_24h.setObjectName("toolButton_24h")
        self.gridLayout_8.addWidget(self.toolButton_24h, 1, 1, 1, 1)
        self.toolButton_ideas = QtWidgets.QToolButton(self.frame)
        self.toolButton_ideas.setMinimumSize(QtCore.QSize(32, 32))
        self.toolButton_ideas.setMaximumSize(QtCore.QSize(40, 40))
        self.toolButton_ideas.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/png/headoutline.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_ideas.setIcon(icon2)
        self.toolButton_ideas.setIconSize(QtCore.QSize(48, 48))
        self.toolButton_ideas.setObjectName("toolButton_ideas")
        self.gridLayout_8.addWidget(self.toolButton_ideas, 1, 3, 1, 1)
        self.toolButton_settings = QtWidgets.QToolButton(self.frame)
        self.toolButton_settings.setMinimumSize(QtCore.QSize(32, 32))
        self.toolButton_settings.setMaximumSize(QtCore.QSize(40, 40))
        self.toolButton_settings.setStyleSheet("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/png/settings39.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_settings.setIcon(icon3)
        self.toolButton_settings.setIconSize(QtCore.QSize(48, 48))
        self.toolButton_settings.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.toolButton_settings.setObjectName("toolButton_settings")
        self.gridLayout_8.addWidget(self.toolButton_settings, 1, 5, 1, 1)
        self.toolButton_tasks = QtWidgets.QToolButton(self.frame)
        self.toolButton_tasks.setMinimumSize(QtCore.QSize(32, 32))
        self.toolButton_tasks.setMaximumSize(QtCore.QSize(40, 40))
        self.toolButton_tasks.setStyleSheet("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/png/checking1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_tasks.setIcon(icon4)
        self.toolButton_tasks.setIconSize(QtCore.QSize(48, 48))
        self.toolButton_tasks.setObjectName("toolButton_tasks")
        self.gridLayout_8.addWidget(self.toolButton_tasks, 1, 2, 1, 1)
        self.horizontalLayout.addWidget(self.frame)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(50, 0))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_9.setContentsMargins(0, 4, 0, 4)
        self.gridLayout_9.setHorizontalSpacing(4)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.toolButton_minimize = QtWidgets.QToolButton(self.frame_2)
        self.toolButton_minimize.setMinimumSize(QtCore.QSize(32, 32))
        self.toolButton_minimize.setMaximumSize(QtCore.QSize(40, 40))
        self.toolButton_minimize.setStyleSheet("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/png/minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_minimize.setIcon(icon5)
        self.toolButton_minimize.setIconSize(QtCore.QSize(48, 48))
        self.toolButton_minimize.setObjectName("toolButton_minimize")
        self.gridLayout_9.addWidget(self.toolButton_minimize, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.pushButton_add_task = QtWidgets.QPushButton(self.page_2)
        self.pushButton_add_task.setObjectName("pushButton_add_task")
        self.horizontalLayout_3.addWidget(self.pushButton_add_task)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.tableWidget_tasks = QtWidgets.QTableWidget(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_tasks.sizePolicy().hasHeightForWidth())
        self.tableWidget_tasks.setSizePolicy(sizePolicy)
        self.tableWidget_tasks.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableWidget_tasks.setStyleSheet("")
        self.tableWidget_tasks.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget_tasks.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget_tasks.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_tasks.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_tasks.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget_tasks.setAlternatingRowColors(True)
        self.tableWidget_tasks.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_tasks.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tableWidget_tasks.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_tasks.setWordWrap(False)
        self.tableWidget_tasks.setObjectName("tableWidget_tasks")
        self.tableWidget_tasks.setColumnCount(8)
        self.tableWidget_tasks.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tasks.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tasks.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tasks.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tasks.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tasks.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tasks.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tasks.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tasks.setHorizontalHeaderItem(7, item)
        self.tableWidget_tasks.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_tasks.horizontalHeader().setStretchLastSection(False)
        self.gridLayout_4.addWidget(self.tableWidget_tasks, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.pushButton_add_idea = QtWidgets.QPushButton(self.page_3)
        self.pushButton_add_idea.setObjectName("pushButton_add_idea")
        self.horizontalLayout_4.addWidget(self.pushButton_add_idea)
        self.gridLayout_5.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.tableWidget_ideas = QtWidgets.QTableWidget(self.page_3)
        self.tableWidget_ideas.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableWidget_ideas.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget_ideas.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget_ideas.setAlternatingRowColors(True)
        self.tableWidget_ideas.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_ideas.setGridStyle(QtCore.Qt.DashLine)
        self.tableWidget_ideas.setWordWrap(False)
        self.tableWidget_ideas.setObjectName("tableWidget_ideas")
        self.tableWidget_ideas.setColumnCount(5)
        self.tableWidget_ideas.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ideas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ideas.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ideas.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ideas.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ideas.setHorizontalHeaderItem(4, item)
        self.tableWidget_ideas.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget_ideas.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_ideas.verticalHeader().setStretchLastSection(False)
        self.gridLayout_5.addWidget(self.tableWidget_ideas, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.webView = QtWebKitWidgets.QWebView(self.page_5)
        self.webView.setUrl(QtCore.QUrl("about:blank"))
        self.webView.setObjectName("webView")
        self.verticalLayout_3.addWidget(self.webView)
        self.stackedWidget.addWidget(self.page_5)
        self.gridLayout_2.addWidget(self.stackedWidget, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.checkBox_always_top = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_always_top.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_always_top.setObjectName("checkBox_always_top")
        self.verticalLayout_2.addWidget(self.checkBox_always_top)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 506, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Memento"))
        self.toolButton_24h.setText(_translate("MainWindow", "..."))
        self.toolButton_ideas.setText(_translate("MainWindow", "..."))
        self.toolButton_settings.setText(_translate("MainWindow", "..."))
        self.toolButton_tasks.setText(_translate("MainWindow", "..."))
        self.toolButton_minimize.setToolTip(_translate("MainWindow", "Minimize"))
        self.toolButton_minimize.setText(_translate("MainWindow", "..."))
        self.pushButton_add_task.setText(_translate("MainWindow", "Add task"))
        self.tableWidget_tasks.setSortingEnabled(True)
        item = self.tableWidget_tasks.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id"))
        item = self.tableWidget_tasks.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Priority"))
        item = self.tableWidget_tasks.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Message"))
        item = self.tableWidget_tasks.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tableWidget_tasks.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Time"))
        item = self.tableWidget_tasks.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "More"))
        item = self.tableWidget_tasks.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Action"))
        item = self.tableWidget_tasks.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Cyclic"))
        self.pushButton_add_idea.setText(_translate("MainWindow", "Add idea"))
        self.tableWidget_ideas.setSortingEnabled(True)
        item = self.tableWidget_ideas.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id"))
        item = self.tableWidget_ideas.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Task"))
        item = self.tableWidget_ideas.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget_ideas.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Description"))
        item = self.tableWidget_ideas.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "More"))
        self.checkBox_always_top.setText(_translate("MainWindow", "Always on top"))

from PyQt5 import QtWebKitWidgets
import resources_rc
